version: "3.9" #
services:
  web:
    image: node:16-alpine3.11
    working_dir: /code
    ports:
      - "5000:3000"
    volumes:
      - .:/code
    container_name: frontend-timer
    command: npm start
    depends_on:
      - server
      - db-timer
    restart: always
  server:
    image: node:16-alpine3.11
    working_dir: /code
    ports:
      - "7000:7000"
    volumes:
      - ./server:/code
    container_name: server
    command: npm run serve
    environment:
      POSTGRES_HOST: db-timer
    depends_on:
      - db-timer
    restart: always
  db-timer:
    image: postgres:13.3
    container_name: pg_timer
    ports:
      - "5432:5432"
    volumes:
      - ./db-files:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD: process.env.DB_PASS
      # POSTGRES_DB: process.env.DB_NAME
      # POSTGRES_USER: process.env.DB_USER
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: timer_db
    
   
      # restart: always
volumes:
  db-files:
