version: "3.9" #
services:
  web:
    image: node:16-alpine3.11
    working_dir: /code
    ports:
      - "5000:3000"
    volumes:
      - .:/code
    container_name: frontend-timer
    command: npm start
    depends_on:
      - server
      - db
    restart: always
  server:
    image: node:16-alpine3.11
    working_dir: /code
    ports:
      - "7000:7000"
    volumes:
      - ./server:/code
    container_name: server
    command: npm run serve
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13.3
    container_name: postgress-for-timer
    ports:
      - "5435:5432"
    volumes:
      - ./db-files:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: process.env.PASS
      POSTGRES_DB: process.env.NAME
      POSTGRES_USER: process.env.USER
      # restart: always
volumes:
  database-data:
